
const E2={cart:{items:[],total:0},currentProduct:null,products:{"tarjetas": {"name": "Tarjetas de Visita", "desc": "El formato imprescindible para tu negocio.", "img": "", "config": [{"id": "tamano", "label": "Tamano", "options": ["85x55 mm", "90x50 mm"]}, {"id": "cantidad", "label": "Cantidad", "options": ["500", "1000", "2000", "5000"]}, {"id": "acabado", "label": "Acabado", "options": ["Normal", "Premium"]}, {"id": "caras", "label": "Impresion", "options": ["1 cara", "2 caras"]}], "prices": {"85x55 mm": {"500": {"Normal": {"1 cara": 45, "2 caras": 55}, "Premium": {"1 cara": 65, "2 caras": 78}}, "1000": {"Normal": {"1 cara": 75, "2 caras": 90}, "Premium": {"1 cara": 105, "2 caras": 125}}, "2000": {"Normal": {"1 cara": 120, "2 caras": 145}, "Premium": {"1 cara": 168, "2 caras": 200}}, "5000": {"Normal": {"1 cara": 250, "2 caras": 300}, "Premium": {"1 cara": 350, "2 caras": 420}}}, "90x50 mm": {"500": {"Normal": {"1 cara": 50, "2 caras": 60}, "Premium": {"1 cara": 72, "2 caras": 86}}, "1000": {"Normal": {"1 cara": 82, "2 caras": 99}, "Premium": {"1 cara": 115, "2 caras": 138}}, "2000": {"Normal": {"1 cara": 132, "2 caras": 160}, "Premium": {"1 cara": 185, "2 caras": 220}}, "5000": {"Normal": {"1 cara": 275, "2 caras": 330}, "Premium": {"1 cara": 385, "2 caras": 462}}}}}},
init(){this.loadCart();this.renderTienda();},
loadCart(){try{const d=JSON.parse(localStorage.getItem('ep2_cart'));if(d)this.cart=d;}catch(e){}},
saveCart(){localStorage.setItem('ep2_cart',JSON.stringify(this.cart));this.updateCartUI();},
showSec(id){document.querySelectorAll('.sec-c').forEach(s=>s.style.display='none');const el=document.getElementById('sec_'+id);if(el)el.style.display='block';else if(id==='home'||id==='presupuesto'||id==='contacto'){/* Dynamic sections rendered into #app, just ensure app is visible */}if(id==='tienda')this.renderTienda();window.scrollTo({top:0,behavior:'smooth'});},
renderTienda(){const d=document.getElementById('app');let h='<div class="sec"><div class="si"><h2 class="st">Todos los <span>Productos</span></h2><p class="ss">Elige, configura y recibe tu pedido.</p><div class="pg">';for(const[id,p]of Object.entries(this.products)){const m=this.getMinPrice(id);h+='<div class="pc"><div class="pc-i">'+(p.img?'<img src="'+p.img+'">':'<div style="font-size:40px;opacity:.2">&#x1F4C4;</div>')+'</div><div class="pc-b"><h3>'+p.name+'</h3><div class="pd">'+p.desc+'</div><div class="pp">Desde '+m+' €</div><div class="pa"><button class="btn btn-p btn-sm" onclick="E2.openConfig(\''+id+'\')">Configurar</button><button class="btn btn-s btn-sm" onclick="E2.showSec(\'presupuesto\')">Presupuesto</button></div></div></div>';}d.innerHTML=h+'</div></div></div>';},
getMinPrice(pid){const p=this.products[pid];if(!p||!p.prices)return'Consultar';let m=Infinity;const w=o=>{if(typeof o==='object'){for(const v of Object.values(o))w(v);}else if(typeof o==='number'&&o<m)m=o;};w(p.prices);return m===Infinity?'Consultar':m.toFixed(2);},
getConfigPrice(pid,vals){const p=this.products[pid];if(!p||!p.prices)return null;try{let c=p.prices;for(const v of vals)c=c[v];return typeof c==='number'?c:null;}catch(e){return null;}},
openConfig(pid){this.currentProduct=pid;const p=this.products[pid];const d=document.getElementById('app');let h='<div class="sec"><div class="si"><a href="#" onclick="E2.showSec(\'tienda\')" style="color:var(--c2);text-decoration:none;font-size:14px;display:inline-block;margin-bottom:16px">&larr; Volver a tienda</a><div class="conf-layout"><div><h2 style="font-size:clamp(22px,3vw,28px);font-weight:800">'+p.name+'</h2><p style="color:var(--text-l);margin:8px 0 16px;font-size:14px">'+p.desc+'</p>';if(p.img)h+='<img src="'+p.img+'" style="width:100%;border-radius:var(--r);max-height:250px;object-fit:cover">';else h+='<div style="background:var(--bg-a);border-radius:var(--r);height:200px;display:flex;align-items:center;justify-content:center;font-size:60px;opacity:.15">&#x1F4C4;</div>';h+='<div class="conf-resumen" id="configSummary" style="margin-top:16px"><strong>Selecciona las opciones</strong> para ver el precio.</div></div><div class="conf"><div class="disclaimer" style="font-size:12px;margin-bottom:16px"><strong>&#x2139;</strong> El precio se actualiza automaticamente al cambiar cualquier opcion.</div><div id="configForm">';for(const c of p.config){h+='<div class="cg"><label>'+c.label+'</label><select id="cfg_'+c.id+'" onchange="E2.updateConfigPrice()">';for(const o of c.options)h+='<option value="'+o.replace(/'/g,"\\'")+'">'+o+'</option>';h+='</select></div>';}h+='<div class="cg"><label>Diseno</label><select id="cfg_diseno" onchange="E2.updateConfigPrice()"><option value="tengo">Ya tengo mi diseno</option><option value="necesito">Necesito diseno (+39,90€)</option></select></div><div class="cg"><div class="file-zone" onclick="document.getElementById(\'designFile\').click()">&#x1F4CE; Sube tu diseno (PDF, JPG, PNG, AI, EPS)<input type="file" id="designFile" accept=".pdf,.jpg,.png,.ai,.eps" style="display:none" onchange="E2.fileSelected()"></div><div id="fileName" style="font-size:12px;color:var(--text-l);margin-top:4px"></div></div><div class="conf-total" id="configTotal">Selecciona opciones <span class="iva">IVA no incluido</span></div><div style="display:flex;gap:8px;margin-top:12px"><button class="btn btn-p" style="flex:1;justify-content:center" onclick="E2.addConfigured()">AÑADIR AL CARRITO</button><button class="btn btn-s" style="flex:1;justify-content:center" onclick="E2.showSec(\'presupuesto\')">SOLICITAR PRESUPUESTO</button></div></div></div></div></div>';d.innerHTML=h;this.updateConfigPrice();},
getConfigValues(){const p=this.products[this.currentProduct];if(!p)return[];return p.config.map(c=>{const e=document.getElementById('cfg_'+c.id);return e?e.value:'';});},
updateConfigPrice(){const v=this.getConfigValues();let p=this.getConfigPrice(this.currentProduct,v);const de=document.getElementById('cfg_diseno');const dc=(de&&de.value==='necesito')?39.90:0;const t=p!==null?p+dc:null;const s=document.getElementById('configSummary');const pd=this.products[this.currentProduct];if(s&&p!==null){let items=[];for(let i=0;i<pd.config.length;i++)items.push(pd.config[i].label+': '+v[i]);if(dc>0)items.push('Diseno: E-print 2');s.innerHTML='<strong>Configuracion:</strong> '+items.join(' | ');}else if(s){s.innerHTML='<span style="color:var(--c7)">&#x26A0; Sin precio disponible. <a href="#" onclick="E2.showSec(\'presupuesto\')">Solicitar presupuesto</a></span>';}const tot=document.getElementById('configTotal');if(tot&&t!==null)tot.innerHTML=t.toFixed(2)+' € <span class="iva">+ IVA</span>';else if(tot)tot.innerHTML='Consultar precio <span class="iva">IVA no incluido</span>';},
fileSelected(){const f=document.getElementById('designFile');const n=document.getElementById('fileName');if(f&&f.files[0])n.textContent='\u2705 '+f.files[0].name+' ('+(f.files[0].size/1024).toFixed(0)+' KB)';},
addConfigured(){const v=this.getConfigValues();const p=this.getConfigPrice(this.currentProduct,v);if(p===null){alert('Selecciona todas las opciones.');return;}const de=document.getElementById('cfg_diseno');const dc=(de&&de.value==='necesito')?39.90:0;const t=p+dc;const pd=this.products[this.currentProduct];let desc=v.join(' · ');if(dc>0)desc+=' · Diseno E-print 2';this.cart.items.push({id:this.currentProduct+'-'+Date.now(),name:pd.name,config:desc,price:t,qty:1});this.saveCart();this.showSec('tienda');this.toggleCart();},
toggleCart(){document.getElementById('cartS').classList.toggle('o');},
updateCartUI(){document.getElementById('cartC').textContent=this.cart.items.length;const it=document.getElementById('cartItems');if(!this.cart.items.length){it.innerHTML='<p style="color:var(--text-l);text-align:center;padding:40px 0">Carrito vacio</p>';document.getElementById('cartT').textContent='0,00€';document.getElementById('cartIva').textContent='';return;}let h='';let t=0;for(let i=0;i<this.cart.items.length;i++){const x=this.cart.items[i];t+=x.price;h+='<div class="ci"><div class="ci-info"><h4>'+x.name+'</h4><p>'+x.config+'</p></div><div class="ci-price">'+x.price.toFixed(2)+'€</div><div class="ci-rm" onclick="E2.removeFromCart('+i+')">&times;</div></div>';}it.innerHTML=h;document.getElementById('cartT').textContent=t.toFixed(2)+'€';document.getElementById('cartIva').textContent='IVA 21%: '+(t*0.21).toFixed(2)+' | Total: '+(t*1.21).toFixed(2)+'€';},
removeFromCart(i){this.cart.items.splice(i,1);this.saveCart();},
checkout(){if(!this.cart.items.length){alert('Carrito vacio');return;}const n=prompt('Nombre completo:');if(!n)return;const e=prompt('Email:');if(!e)return;const t=this.cart.items.reduce((s,i)=>s+i.price,0);const o={id:'E2-PRINT-'+Date.now().toString(36).toUpperCase(),date:new Date().toLocaleString('es-ES'),items:[...this.cart.items],total:t,client:{name:n,email:e},status:'PEDIDO RECIBIDO'};let ors=[];try{ors=JSON.parse(localStorage.getItem('ep2_orders'))||[]}catch(ex){}ors.push(o);localStorage.setItem('ep2_orders',JSON.stringify(ors));this.cart.items=[];this.saveCart();this.toggleCart();alert('\u2705 Pedido '+o.id+' recibido. Te enviaremos la confirmacion a '+e+'.');}
};document.addEventListener('DOMContentLoaded',()=>E2.init());
