const E2={cart:{items:[],total:0},currentProduct:null,products:{"tarjetas": {"name": "Tarjetas de Visita", "desc": "El formato imprescindible para tu negocio.", "img": "assets/tarjetas_visita.png", "config": [{"id": "tamano", "label": "Tamaño", "options": ["85x55 mm", "90x50 mm"]}, {"id": "cantidad", "label": "Cantidad", "options": ["500", "1000", "2000", "5000"]}, {"id": "acabado", "label": "Acabado", "options": ["Normal", "Premium"]}, {"id": "caras", "label": "Impresión", "options": ["1 cara", "2 caras"]}], "prices": {"85x55 mm": {"500": {"Normal": {"1 cara": 45, "2 caras": 55}, "Premium": {"1 cara": 65, "2 caras": 78}}, "1000": {"Normal": {"1 cara": 75, "2 caras": 90}, "Premium": {"1 cara": 105, "2 caras": 125}}, "2000": {"Normal": {"1 cara": 120, "2 caras": 145}, "Premium": {"1 cara": 168, "2 caras": 200}}, "5000": {"Normal": {"1 cara": 250, "2 caras": 300}, "Premium": {"1 cara": 350, "2 caras": 420}}}, "90x50 mm": {"500": {"Normal": {"1 cara": 50, "2 caras": 60}, "Premium": {"1 cara": 72, "2 caras": 86}}, "1000": {"Normal": {"1 cara": 82, "2 caras": 99}, "Premium": {"1 cara": 115, "2 caras": 138}}, "2000": {"Normal": {"1 cara": 132, "2 caras": 160}, "Premium": {"1 cara": 185, "2 caras": 220}}, "5000": {"Normal": {"1 cara": 275, "2 caras": 330}, "Premium": {"1 cara": 385, "2 caras": 462}}}},"flyers": {"name": "Flyers", "desc": "Promoción atractiva y memorable.", "img": "", "config": [], "prices": {}}}};

E2.init=function(){this.loadCart();this.renderHome();};

E2.loadCart=function(){try{var d=JSON.parse(localStorage.getItem("ep2_cart"));if(d)this.cart=d;}catch(e){}};

E2.saveCart=function(){localStorage.setItem("ep2_cart",JSON.stringify(this.cart));this.updateCartUI();};

E2.showSec=function(id){document.querySelectorAll(".sec-c").forEach(function(s){s.style.display="none";});var el=document.getElementById("sec_"+id);if(el)el.style.display="block";if(id==="tienda")this.renderTienda();if(id==="presupuesto")this.renderPresupuesto();if(id==="home")this.renderHome();window.scrollTo({top:0,behavior:"smooth"});};

E2.renderHome=function(){var d=document.getElementById("app");var h='<div class="sec"><div class="si"><div style="text-align:center"><h1 style="font-size:clamp(28px,4vw,36px);font-weight:800;margin-bottom:16px;background:var(--gradient);-webkit-background-clip:text;-webkit-text-fill-color:transparent">Diseño e Impresión Profesional</h1><p style="font-size:clamp(16px,2vw,18px);color:var(--text-l);max-width:640px;margin:0 auto 24px;line-height:1.6">Calidad premium, atención personalizada. Tarjetas, flyers, menús y más a tu medida.</p></div><div class="hero-btns" style="margin-top:32px"><a href="#" class="btn btn-p btn-lg" onclick="E2.showSec('tienda')">Ver Servicios</a><a href="#" class="btn btn-s btn-lg" onclick="E2.showSec('presupuesto')">Solicitar Presupuesto</a></div></div></div>';d.innerHTML=h;};

E2.renderTienda=function(){var d=document.getElementById("app");var h='<div class="sec"><div class="si"><h2 class="st">Todos los <span>Productos</span></h2><p class="ss">Elige, configura y recibe tu pedido.</p><div class="pg">';for(var id in this.products){var p=this.products[id];var m=this.getMinPrice(id);h+='<div class="pc"><div class="pc-i">'+(p.img?"<img src='"+p.img+"' alt='"+p.name+"'>":"<div style="font-size:40px;opacity:.2">&#x1F4C4;</div>")+'</div><div class="pc-b"><h3>'+p.name+'</h3><div class="pd">'+p.desc+'</div><div class="pp">'+m+' €</div><div class="pa"><button class="btn btn-p btn-sm" onclick="E2.openConfig(''+id+'')">Configurar</button><button class="btn btn-s btn-sm" onclick="E2.showSec('presupuesto')">Presupuesto</button></div></div></div>';}h+='</div></div></div>';d.innerHTML=h;this.renderCart();};

E2.renderCart=function(){var d=document.getElementById("app");var cartHtml='<div class="cart-s" id="cartS"><div class="cart-h"><h3>Carrito</h3><span class="close" onclick="E2.toggleCart()">&times;</span></div><div class="cart-items" id="cartItems"></div><div class="cart-f"><div class="ct">Total: <span id="cartT">0,00€</span></div><div id="cartIva" style="font-size:12px;color:var(--text-l);margin-bottom:12px"></div><button class="btn btn-p" style="width:100%" onclick="E2.checkout()">Finalizar Pedido</button></div></div>';d.insertAdjacentHTML("beforeend",cartHtml);this.updateCartUI();};

E2.renderPresupuesto=function(){var d=document.getElementById("app");var h='<div class="sec"><div class="si"><h2 class="st">Solicita tu <span>Presupuesto</span></h2><p class="ss">Cuéntanos qué necesitas y te enviamos un presupuesto sin compromiso.</p><div class="conf"><form id="budgetForm" onsubmit="E2.sendBudget(event)"><div class="conf-layout"><div><div class="cg"><label>Nombre</label><input type="text" id="b_name" required placeholder="Tu nombre"></div><div class="cg"><label>Email</label><input type="email" id="b_email" required placeholder="tu@email.com"></div><div class="cg"><label>Teléfono</label><input type="tel" id="b_phone" required placeholder="+34 695 60 26 25"></div><div class="cg"><label>Producto</label><select id="b_product"><option value="Tarjetas de Visita">Tarjetas de Visita</option><option value="Flyers">Flyers</option><option value="Menús">Menús</option><option value="Manteles">Manteles</option><option value="Carteles">Carteles</option><option value="Pegatinas">Pegatinas</option><option value="Fidelización">Fidelización</option><option value="Otro">Otro</option></select></div></div><div><div class="cg"><label>Cantidad aproximada</label><input type="number" id="b_qty" min="1" placeholder="Ej: 1000"></div><div class="cg"><label>Tamaño / Formato</label><input type="text" id="b_size" placeholder="Ej: 85x55 mm"></div><div class="cg"><label>Acabado</label><input type="text" id="b_finish" placeholder="Ej: Mate, Brillo, UV..."></div><div class="cg"><label>Comentarios</label><textarea id="b_comments" placeholder="Detalles adicionales..." style="width:100%;padding:12px;border:1px solid var(--border);border-radius:var(--rs);min-height:120px;font-family:inherit"></textarea></div></div></div><div style="margin-top:20px"><button type="submit" class="btn btn-p" style="width:100%">Enviar Presupuesto</button></div></form></div></div></div>';d.innerHTML=h;};

E2.sendBudget=function(e){e.preventDefault();var n=document.getElementById("b_name").value;var em=document.getElementById("b_email").value;var ph=document.getElementById("b_phone").value;var pr=document.getElementById("b_product").value;var qt=document.getElementById("b_qty").value;var sz=document.getElementById("b_size").value;var fi=document.getElementById("b_finish").value;var cm=document.getElementById("b_comments").value;var body="Presupuesto E-print 2\n\nNombre: "+n+"\nEmail: "+em+"\nTeléfono: "+ph+"\nProducto: "+pr+"\nCantidad: "+qt+"\nTamaño: "+sz+"\nAcabado: "+fi+"\nComentarios: "+cm;var subject="Presupuesto E-print 2 - "+pr+" - "+n;fetch("https://formsubmit.co/eprintdos2026@gmail.com",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:n,email:em,subject:subject,message:body,text:body})}).then(function(r){if(r.ok){alert("✅ Presupuesto enviado. Te contactaremos pronto.");document.getElementById("budgetForm").reset();}else{alert("Error al enviar. Inténtalo de nuevo.");}}).catch(function(err){alert("Presupuesto recibido. Nos pondremos en contacto contigo.");console.log("Formsubmit fallback:",err);});};

E2.toggleCart=function(){var s=document.getElementById("cartS");if(s)s.classList.toggle("o");var it=document.getElementById("cartItems");if(it&&!this.cart.items.length){it.innerHTML="<p style="color:var(--text-l);text-align:center;padding:40px 0">Carrito vacío</p>";}this.updateCartUI();};

E2.updateCartUI=function(){var cc=document.getElementById("cartC");if(cc)cc.textContent=this.cart.items.length;var it=document.getElementById("cartItems");if(!it)return;if(!this.cart.items.length){it.innerHTML="<p style="color:var(--text-l);text-align:center;padding:40px 0">Carrito vacío</p>";var ct=document.getElementById("cartT");if(ct)ct.textContent="0,00€";var ci=document.getElementById("cartIva");if(ci)ci.textContent="";return;}var h="";var t=0;for(var i=0;i<this.cart.items.length;i++){var x=this.cart.items[i];t+=x.price;h+="<div class="ci"><div class="ci-info"><h4>"+x.name+"</h4><p>"+x.config+"</p></div><div class="ci-price">"+x.price.toFixed(2)+"€</div><div class="ci-rm" onclick="E2.removeFromCart("+i+")">×</div></div>";}it.innerHTML=h;var ct=document.getElementById("cartT");if(ct)ct.textContent=t.toFixed(2)+"€";var ci=document.getElementById("cartIva");if(ci)ci.textContent="IVA 21%: "+(t*0.21).toFixed(2)+" | Total: "+(t*1.21).toFixed(2)+"€";};

E2.removeFromCart=function(i){this.cart.items.splice(i,1);this.saveCart();};

E2.getMinPrice=function(pid){var p=this.products[pid];if(!p||!p.prices)return"Consultar";var m=Infinity;var w=function(o){if(typeof o==="object"){for(var v in Object.values(o))w(o[v]);}else if(typeof o==="number"&&o<m)m=o;};w(p.prices);return m===Infinity?"Consultar":m.toFixed(2);};

E2.getConfigPrice=function(pid,vals){var p=this.products[pid];if(!p||!p.prices)return null;try{var c=p.prices;for(var i=0;i<vals.length;i++)c=c[vals[i]];return typeof c==="number"?c:null;}catch(e){return null;}};

E2.openConfig=function(pid){this.currentProduct=pid;var p=this.products[pid];var d=document.getElementById("app");var h='<div class="sec"><div class="si"><a href="#" onclick="E2.showSec('tienda')" style="color:var(--c2);text-decoration:none;font-size:14px;display:inline-block;margin-bottom:16px">&larr; Volver a tienda</a><div class="conf-layout"><div><h2 style="font-size:clamp(22px,3vw,28px);font-weight:800">'+p.name+'</h2><p style="color:var(--text-l);margin:8px 0 16px;font-size:14px">'+p.desc+'</p>';if(p.img)h+='<img src="'+p.img+"' style="width:100%;border-radius:var(--r);max-height:250px;object-fit:cover">';else h+='<div style="background:var(--bg-a);border-radius:var(--r);height:200px;display:flex;align-items:center;justify-content:center;font-size:60px;opacity:.15">&#x1F4C4;</div>';h+='<div class="conf-resumen" id="configSummary" style="margin-top:16px"><strong>Selecciona las opciones</strong> para ver el precio.</div></div><div class="conf"><div class="disclaimer" style="font-size:12px;margin-bottom:16px"><strong>&#x2139;</strong> El precio se actualiza automaticamente al cambiar cualquier opcion.</div><div id="configForm">';for(var c=0;c<p.config.length;c++){var cfg=p.config[c];h+='<div class="cg"><label>'+cfg.label+'</label><select id="cfg_'+cfg.id+"" onchange="E2.updateConfigPrice()">';for(var o=0;o<cfg.options.length;o++)h+='<option value="'+cfg.options[o].replace(/'/g,"\\'")+"'"+cfg.options[o]+"</option>";h+="</select></div>";}h+='<div class="cg"><label>Diseno</label><select id="cfg_diseno" onchange="E2.updateConfigPrice()"><option value="tengo">Ya tengo mi diseno</option><option value="necesito">Necesito diseno (+39,90€)</option></select></div><div class="cg"><div class="file-zone" onclick="document.getElementById(\'designFile\').click()">📁 Sube tu diseno (PDF, JPG, PNG, AI, EPS)<input type="file" id="designFile" accept=".pdf,.jpg,.png,.ai,.eps" style="display:none" onchange="E2.fileSelected()"></div><div id="fileName" style="font-size:12px;color:var(--text-l);margin-top:4px"></div></div><div class="conf-total" id="configTotal" style="margin-top:20px;text-align:right;font-size:26px;font-weight:800">-- € <span class="iva" style="font-size:14px;font-weight:400;color:var(--text-l)">+ IVA</span></div></div></div></div>';d.innerHTML=h;};

E2.getConfigValues=function(){var p=this.products[this.currentProduct];if(!p)return[];var vals=[];for(var i=0;i<p.config.length;i++){var e=document.getElementById("cfg_"+p.config[i].id);if(e)vals.push(e.value);}return vals;};

E2.updateConfigPrice=function(){var v=this.getConfigValues();var p=this.getConfigPrice(this.currentProduct,v);var de=document.getElementById("cfg_diseno");var dc=(de&&de.value==="necesito")?39.90:0;var t=p!==null?p+dc:null;var s=document.getElementById("configSummary");var pd=this.products[this.currentProduct];if(s&&p!==null){var items=[];for(var i=0;i<pd.config.length;i++)items.push(pd.config[i].label+": "+v[i]);if(dc>0)items.push("Diseno: E-print 2");s.innerHTML="<strong>Configuracion:</strong> "+items.join(" | ");}else if(s){s.innerHTML="<span style="color:var(--c7)">⚠ Sin precio disponible. <a href="#" onclick="E2.showSec('presupuesto')">Solicitar presupuesto</a></span>";}var tot=document.getElementById("configTotal");if(tot&&t!==null)tot.innerHTML=t.toFixed(2)+" € <span class="iva">+ IVA</span>";else if(tot)tot.innerHTML="Consultar precio <span class="iva">IVA no incluido</span>";};

E2.fileSelected=function(){var f=document.getElementById("designFile");var n=document.getElementById("fileName");if(f&&f.files[0])n.textContent="✅ "+f.files[0].name+" ("+(f.files[0].size/1024).toFixed(0)+" KB)";};

E2.addConfigured=function(){var v=this.getConfigValues();var p=this.getConfigPrice(this.currentProduct,v);if(p===null){alert("Selecciona todas las opciones.");return;}var de=document.getElementById("cfg_diseno");var dc=(de&&de.value==="necesito")?39.90:0;var t=p+dc;var pd=this.products[this.currentProduct];var desc=v.join(" · ");if(dc>0)desc+=" · Diseno E-print 2";this.cart.items.push({id:this.currentProduct+"-"+Date.now(),name:pd.name,config:desc,price:t,qty:1});this.saveCart();this.showSec("tienda");this.toggleCart();},

E2.checkout=function(){if(!this.cart.items.length){alert("Carrito vacio");return;}var n=prompt("Nombre completo:");if(!n)return;var e=prompt("Email:");if(!e)return;var t=this.cart.items.reduce(function(s,i){return s+i.price;},0);var o={id:"E2-PRINT-"+Date.now().toString(36).toUpperCase(),date:new Date().toLocaleString("es-ES"),items:[].concat(this.cart.items),total:t,client:{name:n,email:e},status:"PEDIDO RECIBIDO"};var ors=[];try{ors=JSON.parse(localStorage.getItem("ep2_orders"))||[]}catch(ex){}ors.push(o);localStorage.setItem("ep2_orders",JSON.stringify(ors));this.cart.items=[];this.saveCart();this.toggleCart();alert("✅ Pedido "+o.id+" recibido. Te enviaremos la confirmacion a "+e+".");}};

document.addEventListener("DOMContentLoaded",function(){E2.init();});